version: "3"

services:
  jenkinsci:
    image: "jenkinsci/blueocean"
    container_name: "jenkinsci"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins-data:/var/jenkins_home
