version: "3"

services:
    php7:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php7
        volumes:
            - ~/work:/work:rw
        ports:
            - 9001:9000
        networks:
            - app
networks:
    app:
        external: true