version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./log:/var/log/rabbitmq/log:rw
    networks:
      - app
networks:
  app:
    external: true