version: "3"

services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    command: [--default-authentication-plugin=mysql_native_password, --sql_mode=]
    ports:
      - "3306:3306"
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ~/work:/work:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app
networks:
  app:
    external: true