version: "3"

services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - app
networks:
  app:
    external: true