version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    restart: always
    privileged: true #特权模式
    command: [--auth] # 第一次启动去除，创建用户和库之后在加上
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: tire
      MONGO_USERNAME: tire
      MONGO_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes: 
      - ./data:/data/db:rw
      - ./logs:/var/log/mongodb:rw
      - ./conf:/data/configdb:rw
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:rw
    #command: mongod --config /etc/mongo/mongod.conf
networks:
  default:
      external:
        name: app