version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes: 
      - ./data:/data/db:rw
      - ./log:/var/log/mongodb:rw
networks:
  default:
      external:
        name: app