version: '3'

services: 
  redis:
    image: redis:5.0.4
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data:rw
    restart: always
    privileged: true
    networks:
      - app
networks:
  app:
    external: true